version: "3.8"

services:
  api:
    container_name: picpay-desafio-backend-api
    build: 
      context: .
      target: ${API_ENV} 
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "${API_PORT}:3000"
    volumes:
      - .:/app

  postgres:
    image: postgres:15.3
    container_name: picpay-desafio-backend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./.docker/postgres/data:/data/postgres
    ports:
      - "${POSTGRES_PORT}:5432"

  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: picpay-desafio-backend-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_UI_PORT}:15672
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq

