version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picpay-desafio-backend-api
    restart: unless-stopped
    ports:
      - 3000:3000

  postgres:
    image: postgres:15.3
    container_name: picpay-desafio-backend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./.docker/postgres/data:/data/postgres

  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: picpay-desafio-backend-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/log/:/var/log/rabbitmq

  redis:
    image: redis:7.2.4-alpine
    container_name: picpay-desafio-backend-redis
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./.docker/redis/data:/data
