version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: picpay-desafio-backend-api
    restart: unless-stopped
    ports:
      - 8080:8080

  postgres:
    image: postgres:15.3
    container_name: picpay-desafio-backend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: picpay-desafio-backend-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.2.4-alpine
    container_name: picpay-desafio-backend-redis
    restart: unless-stopped
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: picpay-desafio-backend-prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise:10.4.2-ubuntu
    container_name: picpay-desafio-backend-grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
