services:
  api:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: gsa-bank-api
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ..:/home/app
    depends_on:
      - postgres
      - rabbitmq
      - redis

  postgres:
    image: postgres:15.3
    container_name: gsa-bank-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /data/postgres
    ports:
      - 5432:5432

  rabbitmq:
    image: rabbitmq:3.13.1-management-alpine
    container_name: gsa-bank-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7.2.4-alpine
    container_name: gsa-bank-redis
    restart: unless-stopped
    ports:
      - 6379:6379

  prometheus:
    image: prom/prometheus:v2.51.2
    container_name: gsa-bank-prometheus
    restart: unless-stopped
    ports:
      - 9090:9090
    volumes:
      - ../prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise:10.4.2-ubuntu
    container_name: gsa-bank-grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=grafana
      - GF_SECURITY_ADMIN_PASSWORD=grafana
